# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#

name: Cache

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: "${{ matrix.os }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-15

      - name: Install LLVM and Clang
        uses: ./
        with:
          version: "15"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

  test-cloud-cache:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: "${{ matrix.os }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM and Clang
        uses: ./
        with:
          version: "15"
          remote-cached: true
